version: '4.16.1'
services:
  dev-db:
    image: postgres:15.1
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alexpass
      POSTGRES_DB: nestjs_backend
    networks:
      - alexlato
networks:
  alexlato:
